apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    name: postgres-pv
spec:
  capacity:
    storage: 1Gi # taille du volume de stockage
  accessModes:
    - ReadWriteMany # mode d'accès autorisés pour le volume
  persistentVolumeReclaimPolicy: Retain # politique de récupération de la donnée
  storageClassName: ""
  hostPath:
    path: /data/postgres
